on: push 
jobs: 
  build-node: 
    runs-on: ubuntu-latest
    containter: node:16
    steps: 
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node service-worker.js